labels:
  - name: 'active'
    labeled:
      issue:
        body: |
          **🎉 恭喜，友链添加成功！**

          稍后片刻刷新网页就可以看到您的链接。

          > 如果您的站点信息发生了变动，请直接修改本 issue 中的相关内容。如需修改链接，请关闭本 issue 后创建一个新的 issue。
  
  - name: 'checklist'
    labeled:
      issue:
        body: |
          **🥹 很遗憾，部分条件未满足～**

          很感谢您的支持，但请等待交换友链的前置条件均已满足后再进行操作。
  
  - name: 'suspend'
    labeled:
      issue:
        body: |
          **👋 请及时添加本站友链**

          距离成功只剩一步之遥了，请把本站添加到您的友链中，然后在下方评论告知。

  - name: '404'
    labeled:
      issue:
        body: |
          **⚠️ 抱歉，您的网站无法访问，现已移动到失效友链中。**

          如果您确认可以正常访问，请在下方评论告知，我会在访问通过后恢复。
