name: Update Packages

on:
  workflow_dispatch:
  schedule:
    # UTC 21:00 -> CST (China) 5:00
    - cron: '0 21 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      commited: ${{ steps.commit.outputs.committed }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x
          cache: pnpm

      - name: Upgrade deps
        run: pnpm up --latest

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@main
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: upgrade deps'
          add: '.'

  build:
    needs: update
    runs-on: ubuntu-latest
    if: needs.update.outputs.commited == 'true'
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x
          cache: pnpm

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
          enable_jekyll: true
