name: MengNianxiaoyao Links

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: pnpm/action-setup@v4.0.0
        with:
            run_install: true
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x
          cache: pnpm

      - name: Lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x
      - uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true

      - name: Typecheck
        run: pnpm run typecheck

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: pnpm/action-setup@v4.0.0
        with:
            run_install: true
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x
          cache: pnpm

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
          enable_jekyll: true
