name: Check Links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '22.14.0'
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Set time zone
        run: |
          sudo timedatectl set-timezone 'Asia/Shanghai'
          echo "CURRENT_DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      
      - name: Generate timestamp SVG
        run: |
          echo '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="226" height="20" role="img" aria-label="last check: ${{ env.CURRENT_DATE }}+08:00"><title>last check: ${{ env.CURRENT_DATE }}+08:00</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="226" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="53" height="20" fill="#555"/><rect x="53" width="173" height="20" fill="#4c1"/><rect width="226" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text aria-hidden="true" x="275" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="430">last check</text><text x="275" y="140" transform="scale(.1)" fill="#fff" textLength="430">last check</text><text aria-hidden="true" x="1385" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="1630">${{ env.CURRENT_DATE }}+08:00</text><text x="1385" y="140" transform="scale(.1)" fill="#fff" textLength="1630">${{ env.CURRENT_DATE }}+08:00</text></g></svg>' >> timestamp.svg
          mv -f timestamp.svg ./public/

      - name: Check links
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: pnpm run check

      - name: Commit changes
        id: push
        uses: EndBug/add-and-commit@main
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'chore: check links'
          add: '.'

      - name: Build
        if: steps.push.outputs.pushed == 'true'
        run: pnpm run build

      - name: Deploy
        if: steps.push.outputs.pushed == 'true'
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
          enable_jekyll: true
          commit_message: 'chore: deploy website'
