name: Issue Labeled Handler

on:
  issues:
    types: 
      - labeled

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1.10.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/label-commenter-config.yml
