name: Issue Created Handler

on:
  issues:
    types: 
      - opened
      - closed
      - edited

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  add-label:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      pushed: ${{ steps.push.outputs.pushed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '22.14.0'
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Script for issue
        env:
          TOKEN: ${{ secrets.TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: pnpm run add

      - name: Check Checkbox Status
        id: checkboxes
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body;
            const status = body.includes('[x] <!-- checklink -->');
            if (status) {
              const updatedBody = body.replace('[x] <!-- checklink -->', '[ ] <!-- checklink -->');
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: updatedBody
              });
            };

      - name: Commit changes
        id: push
        uses: EndBug/add-and-commit@main
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'chore: update link from issues'
          add: '.'

  deploy-pages:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: add-label
    if: needs.add-label.outputs.pushed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '22.14.0'
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Build Links
        run: pnpm run build

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./dist
          destination: ./site

      - name: Copy CNAME
        run: sudo cp ./public/CNAME ./site/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
          enable_jekyll: true
          commit_message: 'chore: deploy website'
